theme: jekyll-theme-tactile

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------

twitter_username: # your twitter user name
linkedin_username: rongchen-li-22b021127 # your LinkedIn user name
github_username: rongchen-li # your github user name
google_analytics: G-HRNKBM7DJ1 # what is google analytics
scholar_userid: y_5mYi0AAAAJ # your Google Scholar ID
orcid_id:  # your ORCID ID
medium_username: # your Medium username
quora_username: # your Quora username
publons_id: # your ID on Publons
research_gate_profile: # research gate profile
blogger_url: # your blogger URL
work_url: # work page URL
keybase_username: # your keybase user name
wikidata_id: # your wikidata id

contact_note: >
  The best way to contact me is via email.
